2025-04-28 04:18:20,459 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5901
2025-04-28 04:18:20,459 INFO: [33mPress CTRL+C to quit[0m
2025-04-28 04:18:20,706 INFO: 127.0.0.1 - - [28/Apr/2025 04:18:20] "GET / HTTP/1.1" 200 -
2025-04-28 04:18:21,886 INFO: 127.0.0.1 - - [28/Apr/2025 04:18:21] "GET / HTTP/1.1" 200 -
2025-04-28 04:18:22,765 INFO: [PID 298302] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:18:22,762 INFO: [PID 298239] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:18:22,773 INFO: Ensured table exists in data/data/blockchain.db
2025-04-28 04:18:22,773 INFO: [PID 298239] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:18:22,774 INFO: [PID 298302] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:18:22,781 INFO: Ensured table exists in data/data/blockchain.db
2025-04-28 04:18:23,041 INFO: Ensured table exists in data/account.db
2025-04-28 04:18:23,090 INFO: Ensured table exists in data/account.db
2025-04-28 04:18:23,102 INFO: Ensured table exists in data/account.db
2025-04-28 04:18:23,130 INFO: Block written successfully.
2025-04-28 04:18:25,118 INFO: Ensured table exists in data/account.db
2025-04-28 04:18:25,469 INFO: [PID 298239] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:18:25,470 INFO: [PID 298239] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-2025-04-28 04:19:23,068 INFO: Ensured table exists in data/account.db
2025-04-28 04:19:23,075 INFO: Ensured table exists in data/account.db
2025-04-28 04:19:23,077 INFO: Ensured table exists in data/account.db
2025-04-28 04:19:25,147 INFO: Ensured table exists in data/account.db
2025-04-28 04:19:25,520 INFO: [PID 298302] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:19:25,521 INFO: [PID 298302] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:19:25,523 INFO: Ensured table exists in data/data/blockchain.db
2025-04-28 04:19:25,523 INFO: [PID 298302] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:19:25,524 INFO: [PID 298302] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:19:25,525 INFO: Ensured table exists in data/data/blockchain.db
2025-04-28 04:19:25,710 INFO: Block written successfully.
attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:19:25,524 INFO: [PID 298302] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:19:25,525 INFO: Ensured table exists in data/data/blockchain.db
2025-04-28 04:19:25,710 INFO: Block written successfully.
